/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import {Contract, ContractTransaction, EventFilter, Signer} from "ethers";
import {Listener, Provider} from "ethers/providers";
import {Arrayish, BigNumber, BigNumberish, Interface} from "ethers/utils";
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription
} from ".";

interface BurnerRoleMockInterface extends Interface {
  functions: {
    addAdmin: TypedFunctionDescription<{encode([account]: [string]): string}>;

    addBurner: TypedFunctionDescription<{encode([account]: [string]): string}>;

    admins: TypedFunctionDescription<{encode([]: []): string}>;

    burners: TypedFunctionDescription<{encode([]: []): string}>;

    isAdmin: TypedFunctionDescription<{encode([account]: [string]): string}>;

    isBurner: TypedFunctionDescription<{encode([account]: [string]): string}>;

    isOwner: TypedFunctionDescription<{encode([]: []): string}>;

    owner: TypedFunctionDescription<{encode([]: []): string}>;

    removeAdmin: TypedFunctionDescription<{
      encode([account]: [string]): string;
    }>;

    removeBurner: TypedFunctionDescription<{
      encode([account]: [string]): string;
    }>;
  };

  events: {
    AdminAdded: TypedEventDescription<{
      encodeTopics([account]: [string | null]): string[];
    }>;

    AdminRemoved: TypedEventDescription<{
      encodeTopics([account]: [string | null]): string[];
    }>;

    BurnerAdded: TypedEventDescription<{
      encodeTopics([account]: [string | null]): string[];
    }>;

    BurnerRemoved: TypedEventDescription<{
      encodeTopics([account]: [string | null]): string[];
    }>;
  };
}

export class BurnerRoleMock extends Contract {
  connect(signerOrProvider: Signer | Provider | string): BurnerRoleMock;
  attach(addressOrName: string): BurnerRoleMock;
  deployed(): Promise<BurnerRoleMock>;

  on(event: EventFilter | string, listener: Listener): BurnerRoleMock;
  once(event: EventFilter | string, listener: Listener): BurnerRoleMock;
  addListener(
    eventName: EventFilter | string,
    listener: Listener
  ): BurnerRoleMock;
  removeAllListeners(eventName: EventFilter | string): BurnerRoleMock;
  removeListener(eventName: any, listener: Listener): BurnerRoleMock;

  interface: BurnerRoleMockInterface;

  functions: {
    addAdmin(
      account: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    addBurner(
      account: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    admins(): Promise<string[]>;

    burners(): Promise<string[]>;

    isAdmin(account: string): Promise<boolean>;

    isBurner(account: string): Promise<boolean>;

    isOwner(): Promise<boolean>;

    owner(): Promise<string>;

    removeAdmin(
      account: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    removeBurner(
      account: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;
  };

  addAdmin(
    account: string,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  addBurner(
    account: string,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  admins(): Promise<string[]>;

  burners(): Promise<string[]>;

  isAdmin(account: string): Promise<boolean>;

  isBurner(account: string): Promise<boolean>;

  isOwner(): Promise<boolean>;

  owner(): Promise<string>;

  removeAdmin(
    account: string,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  removeBurner(
    account: string,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  filters: {
    AdminAdded(account: string | null): EventFilter;

    AdminRemoved(account: string | null): EventFilter;

    BurnerAdded(account: string | null): EventFilter;

    BurnerRemoved(account: string | null): EventFilter;
  };

  estimate: {
    addAdmin(account: string): Promise<BigNumber>;

    addBurner(account: string): Promise<BigNumber>;

    admins(): Promise<BigNumber>;

    burners(): Promise<BigNumber>;

    isAdmin(account: string): Promise<BigNumber>;

    isBurner(account: string): Promise<BigNumber>;

    isOwner(): Promise<BigNumber>;

    owner(): Promise<BigNumber>;

    removeAdmin(account: string): Promise<BigNumber>;

    removeBurner(account: string): Promise<BigNumber>;
  };
}
