/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import {Contract, ContractTransaction, EventFilter, Signer} from "ethers";
import {Listener, Provider} from "ethers/providers";
import {Arrayish, BigNumber, BigNumberish, Interface} from "ethers/utils";
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription
} from ".";

interface PausableInterface extends Interface {
  functions: {
    addAdmin: TypedFunctionDescription<{encode([account]: [string]): string}>;

    admins: TypedFunctionDescription<{encode([]: []): string}>;

    isAdmin: TypedFunctionDescription<{encode([account]: [string]): string}>;

    isOwner: TypedFunctionDescription<{encode([]: []): string}>;

    owner: TypedFunctionDescription<{encode([]: []): string}>;

    pause: TypedFunctionDescription<{encode([]: []): string}>;

    paused: TypedFunctionDescription<{encode([]: []): string}>;

    removeAdmin: TypedFunctionDescription<{
      encode([account]: [string]): string;
    }>;

    unpause: TypedFunctionDescription<{encode([]: []): string}>;
  };

  events: {
    AdminAdded: TypedEventDescription<{
      encodeTopics([account]: [string | null]): string[];
    }>;

    AdminRemoved: TypedEventDescription<{
      encodeTopics([account]: [string | null]): string[];
    }>;

    Paused: TypedEventDescription<{encodeTopics([account]: [null]): string[]}>;

    Unpaused: TypedEventDescription<{
      encodeTopics([account]: [null]): string[];
    }>;
  };
}

export class Pausable extends Contract {
  connect(signerOrProvider: Signer | Provider | string): Pausable;
  attach(addressOrName: string): Pausable;
  deployed(): Promise<Pausable>;

  on(event: EventFilter | string, listener: Listener): Pausable;
  once(event: EventFilter | string, listener: Listener): Pausable;
  addListener(eventName: EventFilter | string, listener: Listener): Pausable;
  removeAllListeners(eventName: EventFilter | string): Pausable;
  removeListener(eventName: any, listener: Listener): Pausable;

  interface: PausableInterface;

  functions: {
    addAdmin(
      account: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    admins(): Promise<string[]>;

    isAdmin(account: string): Promise<boolean>;

    isOwner(): Promise<boolean>;

    owner(): Promise<string>;

    pause(overrides?: TransactionOverrides): Promise<ContractTransaction>;

    paused(): Promise<boolean>;

    removeAdmin(
      account: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    unpause(overrides?: TransactionOverrides): Promise<ContractTransaction>;
  };

  addAdmin(
    account: string,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  admins(): Promise<string[]>;

  isAdmin(account: string): Promise<boolean>;

  isOwner(): Promise<boolean>;

  owner(): Promise<string>;

  pause(overrides?: TransactionOverrides): Promise<ContractTransaction>;

  paused(): Promise<boolean>;

  removeAdmin(
    account: string,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  unpause(overrides?: TransactionOverrides): Promise<ContractTransaction>;

  filters: {
    AdminAdded(account: string | null): EventFilter;

    AdminRemoved(account: string | null): EventFilter;

    Paused(account: null): EventFilter;

    Unpaused(account: null): EventFilter;
  };

  estimate: {
    addAdmin(account: string): Promise<BigNumber>;

    admins(): Promise<BigNumber>;

    isAdmin(account: string): Promise<BigNumber>;

    isOwner(): Promise<BigNumber>;

    owner(): Promise<BigNumber>;

    pause(): Promise<BigNumber>;

    paused(): Promise<BigNumber>;

    removeAdmin(account: string): Promise<BigNumber>;

    unpause(): Promise<BigNumber>;
  };
}
